# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-24 04:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_cliente_colonia'),
        ('catalogo_detalles', '0002_auto_20160605_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fec_venta', models.DateField(default='1900-01-01')),
                ('num_documento', models.CharField(blank=True, default='', max_length=30)),
                ('bln_activa', models.BooleanField(default=True)),
                ('fec_inventario', models.DateField(default='1900-01-01')),
                ('cantidad_pago', models.IntegerField(default=0)),
                ('observaciones', models.CharField(blank=True, default='', max_length=100)),
                ('banco_cliente', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='bancoCliente_venta', to='catalogo_detalles.CatalogoDetalle')),
                ('cliente', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='venta_id_cliente', to='clientes.Cliente')),
                ('metodo_pago', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='metodoPago_venta', to='catalogo_detalles.CatalogoDetalle')),
                ('periodo_pago', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='periodoPago_venta', to='catalogo_detalles.CatalogoDetalle')),
                ('tipo_doc', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='tipoDoc_venta', to='catalogo_detalles.CatalogoDetalle')),
            ],
        ),
    ]
