# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-02 05:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_detalles', '0002_auto_20160605_2200'),
        ('ventas', '0002_auto_20160816_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='empresa',
            field=models.ForeignKey(default=b'0140000', on_delete=django.db.models.deletion.PROTECT, related_name='empresa_venta', to='catalogo_detalles.CatalogoDetalle'),
        ),
    ]
