# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-03 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_venta_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='num_documento',
            field=models.CharField(blank=True, default=b'', error_messages={b'unique': b'El numero de documento ya existe'}, max_length=30, unique=True),
        ),
    ]
