# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-11-12 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_auto_20160902_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='empresa',
            field=models.ForeignKey(default='0140000', on_delete=django.db.models.deletion.PROTECT, related_name='empresa_venta', to='catalogo_detalles.CatalogoDetalle'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='num_documento',
            field=models.CharField(blank=True, default='', error_messages={'unique': 'El numero de documento ya existe'}, max_length=30, unique=True),
        ),
    ]
