# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-02 02:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientesPago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movimiento', models.CharField(default='', max_length=5)),
                ('fecha', models.DateField(default='1900-01-01')),
                ('cargo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('abono', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('observaciones', models.CharField(blank=True, default='', max_length=100)),
                ('ventas', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='venta_id_pagos', to='ventas.Venta')),
            ],
        ),
    ]
