# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-02 05:31
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_pagos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientespago',
            name='movimiento',
        ),
        migrations.AlterField(
            model_name='clientespago',
            name='abono',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='clientespago',
            name='cargo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
