# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-04-17 04:44
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_pagos', '0003_auto_20170502_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientespago',
            name='abono',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=13, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='clientespago',
            name='cargo',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=13, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
