# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 03:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_detalles', '0001_initial'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='calle',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='codigo',
            field=models.CharField(default='', error_messages={'unique': 'El codigo del Proveedor ya existe'}, max_length=7, unique=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='comentarios',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='cp',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='estado',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='proveedor_estado', to='catalogo_detalles.CatalogoDetalle', validators=[django.core.validators.RegexValidator(code='nomatch', message='El catalogo debe empezar con 14 y su longitud de 7', regex='(?=^.{7,7}$)(^014)([0-9]{4})')]),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(default='', error_messages={'unique': 'El nombre del Proveedor ya existe'}, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='numero',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='pais',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='proveedor_pais', to='catalogo_detalles.CatalogoDetalle', validators=[django.core.validators.RegexValidator(code='nomatch', message='El catalogo debe empezar con 14 y su longitud de 7', regex='(?=^.{7,7}$)(^014)([0-9]{4})')]),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='rfc',
            field=models.CharField(default='', max_length=13),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
