# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 03:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_auto_20160503_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='estado',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='proveedor_estado', to='catalogo_detalles.CatalogoDetalle', validators=[django.core.validators.RegexValidator(code='nomatch', message='El catalogo debe empezar con 002 y su longitud de 7', regex='(?=^.{7,7}$)(^002)([0-9]{4})')]),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='pais',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='proveedor_pais', to='catalogo_detalles.CatalogoDetalle', validators=[django.core.validators.RegexValidator(code='nomatch', message='El catalogo debe empezar con 001 y su longitud de 7', regex='(?=^.{7,7}$)(^001)([0-9]{4})')]),
        ),
    ]
