# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 04:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_auto_20160503_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='estado',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='proveedor_estado', to='catalogo_detalles.CatalogoDetalle'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='pais',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='proveedor_pais', to='catalogo_detalles.CatalogoDetalle'),
        ),
    ]
