# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0004_auto_20160503_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='colonia',
            field=models.CharField(default='', max_length=50),
        ),
    ]
