# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 03:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        ('catalogo_detalles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsc_material', models.CharField(blank=True, default='', max_length=100)),
                ('calibre', models.DecimalField(decimal_places=3, default=0.0, max_digits=4)),
                ('ancho', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('largo', models.IntegerField(default=0)),
                ('peso_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('peso_lb', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('num_rollo', models.CharField(blank=True, default='', max_length=30)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('compra', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='compra_detalles_id', to='compras.Compra')),
                ('material', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='compra_detalles_material', to='catalogo_detalles.CatalogoDetalle')),
            ],
        ),
    ]
