# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras_detalles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compradetalle',
            name='compra',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='compra_detalles', to='compras.Compra'),
        ),
    ]
