# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-10 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_detalles', '0002_auto_20160518_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='compradetalle',
            name='validado',
            field=models.BooleanField(default=False),
        ),
    ]
