# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-19 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_detalles', '0003_compradetalle_validado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compradetalle',
            name='peso_kg',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='compradetalle',
            name='peso_lb',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=13),
        ),
    ]
