# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-27 00:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_rollo', models.CharField(blank=True, default='', max_length=30)),
                ('peso_kg', models.DecimalField(decimal_places=5, default=0.0, max_digits=13)),
                ('precio_neto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('venta', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='venta_detalles', to='ventas.Venta')),
            ],
        ),
    ]
