# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-04-17 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_detalles', '0002_ventadetalle_tipo_rollo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventadetalle',
            name='precio_neto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=13),
        ),
    ]
