# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-11-12 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_detalles', '0003_auto_20180416_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventadetalle',
            name='tipo_rollo',
            field=models.ForeignKey(default='0150000', on_delete=django.db.models.deletion.PROTECT, related_name='tipoRollo_venta', to='catalogo_detalles.CatalogoDetalle'),
        ),
    ]
