# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 05:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0005_proveedor_colonia'),
        ('catalogo_detalles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.CharField(default='', error_messages={'unique': 'El numero de invoice ya existe'}, max_length=10, unique=True)),
                ('fec_solicitud', models.DateField(default='1900-01-01')),
                ('fec_aduana', models.DateField(default='1900-01-01')),
                ('fec_inventario', models.DateField(default='1900-01-01')),
                ('fec_real', models.DateField(default='1900-01-01')),
                ('casa_cambio', models.CharField(blank=True, default='', max_length=30)),
                ('precio_dolar', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('transporte', models.CharField(blank=True, default='', max_length=50)),
                ('bln_activa', models.BooleanField(default=True)),
                ('descripcion', models.CharField(blank=True, default='', max_length=100)),
                ('comentarios', models.CharField(blank=True, default='', max_length=100)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compra_id_proveedor', to='proveedores.Proveedor')),
                ('tipo_moneda', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='compra_tipo_moneda', to='catalogo_detalles.CatalogoDetalle')),
            ],
        ),
    ]
