# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-27 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Existencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_rollo', models.CharField(default='', max_length=30)),
                ('entrada_kg', models.DecimalField(decimal_places=5, default=0.0, max_digits=13)),
                ('salida_kg', models.DecimalField(decimal_places=5, default=0.0, max_digits=13)),
                ('id_operacion', models.IntegerField(default=0)),
                ('operacion', models.CharField(blank=True, default='', max_length=10)),
            ],
        ),
    ]
