# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-11-21 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('existencias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='existencia',
            name='fecha',
            field=models.DateField(default=b'1900-01-01'),
        ),
    ]
