# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 23:41
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0004_auto_20160429_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoDetalle',
            fields=[
                ('cdu_catalogo', models.CharField(default='0000000', editable=False, max_length=7, primary_key=True, serialize=False, unique=True)),
                ('num_dcatalogo', models.IntegerField(default=0, help_text='clave consecutiva del detalle del catalogo')),
                ('descripcion1', models.CharField(max_length=100)),
                ('descripcion2', models.CharField(blank=True, max_length=100)),
                ('monto1', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('monto2', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('cdu_default', models.CharField(blank=True, max_length=7)),
                ('catalogos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogos_detalle', to='catalogos.Catalogo')),
            ],
        ),
    ]
