# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogo',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
    ]
