# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_catalogo_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='nombre',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
