# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 05:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo_detalles', '0002_auto_20160605_2200'),
        ('compras_detalles', '0002_auto_20160518_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_compra', models.CharField(default='', max_length=10)),
                ('calibre', models.DecimalField(decimal_places=3, default=0.0, max_digits=4)),
                ('ancho', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('largo', models.IntegerField(default=0)),
                ('codigo_producto', models.CharField(default='', max_length=30)),
                ('num_rollo', models.CharField(blank=True, default='', max_length=30)),
                ('peso_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('peso_lb', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transporte', models.CharField(blank=True, default='', max_length=50)),
                ('precio_libra', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('factor', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('precio_dolar', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('factor_impuesto', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('con_comercializadora', models.BooleanField(default=False)),
                ('factor_kilos', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('valor_kilo_dolar', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('valor_tonelada_pesos', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('valor_kilo_persos', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('valor_final_kilo_pesos', models.DecimalField(decimal_places=4, default=0.0, max_digits=18)),
                ('descripcion', models.CharField(blank=True, default='', max_length=100)),
                ('comentarios', models.CharField(blank=True, default='', max_length=100)),
                ('compra_detalle', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='inventario_id_compra_detalle', to='compras_detalles.CompraDetalle')),
                ('material', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='inventario_detalles_material', to='catalogo_detalles.CatalogoDetalle')),
                ('pais', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='inventario_pais', to='catalogo_detalles.CatalogoDetalle')),
            ],
        ),
    ]
