# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='porc_comercializadora',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=18),
        ),
        migrations.AddField(
            model_name='inventario',
            name='precio_tonelada_dolar',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=18),
        ),
    ]
