# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 19:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0002_auto_20160609_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario',
            old_name='valor_kilo_persos',
            new_name='valor_kilo_pesos',
        ),
    ]
