# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-16 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0005_auto_20160616_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='peso_kg',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=13),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='peso_lb',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=13),
        ),
    ]
