# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-30 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0006_auto_20160616_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='ancho',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='calibre',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=5),
        ),
    ]
