# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2020-11-12 19:45
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_colonia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='limite_credito',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=13, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
